### ISSUE TITLE
unable to use multiple subdomains to a single app using a wildcard

### ISSUE THREAD

**Issue by TBD** [pomdtr/smallweb#16]
trying to use a single small web app for multiple subdomain (eg one.zeno.localhost -> ~/smallweb/zeno)

added to ~/.config/smallweb/config.json - `"*.zeno.localhost": "~/smallweb/zeno"`

**Comment by pomdtr** [comment]
Even though the config format is deprecated, I wonder if we could support this usecase using app directory names:

I'm thinking of taking inspiration from [URL Pattern] api:

ex: `prefix-:name` would match `prefix-*`

Using `:` is quite good because it does not conflict with shell globbing (`*`, `[` and `]` are used in globs).

**Comment by pomdtr** [comment]
Closing this. I'm not planning to add back for wildcard support on a single app for now.
